version: "3.9"

services:
    db:
        image: mysql:8.0
        container_name: e2e-test-db
        ports:
            - "3312:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --skip-character-set-client-handshake
        extra_hosts:
            - "host.docker.internal:host-gateway"
