module.exports = {
    preset: "ts-jest",
    testEnvironment: "node",
    collectCoverage: true,
    coverageReporters: ["lcov", "text"],
    collectCoverageFrom: [
        "src/**/*.ts",
        "!src/**/*.spec.ts",
        "!src/**/*.module.ts",
        "!src/**/main.ts",
        "!src/**/index.ts",
        "!src/**/application.ts",
        "!src/**/*.entity.ts",
        "!src/**/env-keys.const.ts",
        "!**/node_modules/**",
        "!**/dist/**",
        "!**/coverage/**",
        "!src/common/logger/winston.ts",
        "!src/common/response/success-response.dto.ts",
        "!src/common/response/exception-response.dto.ts",
        "!src/common/sentry/instrument.ts",
        "!src/common/swagger/**",
    ],
};
